name: Deploy snapshot with gpg signature to remote repo

on:
 workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      java-distribution:
        required: true
        type: string
        default: 'temurin'
      maven-deployment-repo:
        required: true
        type: string
    secrets:
      repo-username:
        required: true
      repo-password:
        required: true
      gpg_private_key:
        required: true
      gpg_passphrase:
        required: true
   

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          java-version:  ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
          gpg-private-key: ${{ secrets.gpg_private_key }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: |
            [
              {
                "id": "central",
                "name": "Maven Central",
                "url": "https://repo1.maven.org/maven2",
                "releases": {"enabled": "true"},
                "snapshots": {"enabled": "false"}
              },
              {
                "id": "repo",
                "name": "Remote repo",
                "url": "${{ inputs.maven-deployment-repo }}",
                "releases": {"enabled": "true"},
                "snapshots": {"enabled": "true"}
              }
            ]
          servers: |
            [
              {
                "id": "repo",
                "username": "${env.REPO_USERNAME}",
                "password": "${env.REPO_PASSWORD}"
              }
            ]
          output_file: .m2/settings.xml

      - name: print settings.xml
        run: cat .m2/settings.xml
          
      - name: Publish package
        run: mvn --batch-mode deploy -DaltDeploymentRepository=repo::default::${{ inputs.maven-deployment-repo }}  --settings .m2/settings.xml
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          REPO_URL: ${{ inputs.maven-deployment-repo }}
          REPO_USERNAME: ${{ secrets.repo-username }}
          REPO_PASSWORD: ${{ secrets.repo-password }}
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
  tag:         
      runs-on: ubuntu-latest
      needs: [release]
      steps:
        - name: Checkout files
          uses: Bhacaz/checkout-files@v2
          with:
           files: pom.xml
           branch: ${{ github.event.workflow_run.head_branch }}
        - name: Get version from pom.xml
          id: get-version
          uses: JActions/maven-version@v1.2.0
        - name: Create Tag
          uses: negz/create-tag@v1
          with:
            version: ${{ steps.get-version.outputs.version }}
            message: Release version for ${{ steps.get-version.outputs.version }}
            token: ${{ secrets.GITHUB_TOKEN }}
